name: beaver-sim
dependencies:
  - pip
  - python=3.7
  - pip:
    - uvicorn
    - requests
    - pyserial
    - bitstring
    - aiohttp
    - aiohttp-sse-client
    - flake8
    - flake8-black
    - mypy

